#!/bin/sh

##DEBHELPER##

set -e

case "$1" in
    configure)
        target=""
        if grep -q '^DeepComputing FML13V01$' /sys/firmware/devicetree/base/model; then
            if [ -e /dev/disk/by-partlabel/loader1 ] && [ -e /dev/disk/by-partlabel/loader2 ]; then
                dd if=/usr/lib/u-boot-fml13v01/u-boot-spl.bin.normal.out of=/dev/disk/by-partlabel/loader1 bs=1M conv=fsync
                dd if=/usr/lib/u-boot-fml13v01/u-boot.itb of=/dev/disk/by-partlabel/loader2 bs=1M conv=fsync
            fi
        fi
        ;;
esac

exit 0
